1.What is a parameter?
      ANS.A parameter is a numerical value that defines a population characteristic (e.g., mean μ, standard deviation σ).

In Machine Learning, parameters are the internal values a model learns during training (e.g., weights and biases in neural networks).

2.What is correlation?What does negative correlation mean?
     ANS.Correlation is a statistical measure that shows the strength and direction of the relationship between two variables.

It ranges from –1 to +1.
A negative correlation means that as one variable increases, the other decreases.

Example: Price of a product ↑ → Demand ↓.

3. Define Machine Learning. What are the main components in Machine Learning?

      ANS.Machine Learning (ML) is a field of AI that allows systems to learn patterns from data and make predictions without being explicitly programmed.

Main components:

Data (input features and labels)

Model (algorithm to map input → output)

Loss function (measures prediction error)

Optimizer (updates parameters to minimize loss)

Evaluation (metrics to test performance).

4.How does loss value help in determining whether the model is good or not?

      ANS.Loss value measures how far predictions are from actual outputs.

Lower loss → better model fit.

Helps track learning progress during training.

5.What are continuous and categorical variables?

      ANS.Continuous: Numeric values with infinite possible outcomes (e.g., height, weight).

Categorical: Values divided into categories or labels (e.g., gender, color).

6.How do we handle categorical variables in Machine Learning? What are the common techniques?

        ANS.Techniques:

Label Encoding – converts categories into integers.

One-Hot Encoding – creates binary dummy variables.

Ordinal Encoding – preserves order in categories.

7.What do you mean by training and testing a dataset?

      ANS.Training set: Used to train the model and learn patterns.

Test set: Used to evaluate how well the model generalizes to unseen data.

8.What is sklearn.preprocessing?

      ANS.A scikit-learn module for preparing data before modeling.

Includes tools for scaling, normalization, encoding categorical variables, imputation, etc.

9.What is a Test set?

      ANS.A dataset that is kept aside during training and used only to evaluate model performance.

10.How do we split data for model fitting (training and testing) in Python?
 How do you approach a Machine Learning problem?

      ANS.Using train_test_split from sklearn:
      
To Approach a Machine Learning problem
Understand the problem.

Collect and clean data.

Perform EDA (exploratory data analysis).

Preprocess (scaling, encoding, splitting).

Select model(s).

Train model(s).

Evaluate performance.

Tune hyperparameters.

Deploy and monitor.

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

11.Why do we have to perform EDA before fitting a model to the data?

ANS.EDA helps understand data distribution, missing values, outliers, correlations, and relationships.

Prevents wrong assumptions and ensures proper preprocessing.

12.What is correlation?
ANS.Correlation is a statistical measure that shows the strength and direction of the relationship between two variables.

It ranges from –1 to +1.

13.What does negative correlation mean?
ANS.A negative correlation means that as one variable increases, the other decreases.

Example: Price of a product ↑ → Demand ↓.

14.How can you find correlation between variables in Python?

ANS.

In [8]:
import pandas as pd

# Create a sample DataFrame to demonstrate df.corr()
data = {'col1': [1, 2, 3, 4, 5],
        'col2': [5, 4, 3, 2, 1],
        'col3': [1, 2, 1, 2, 1]}
df = pd.DataFrame(data)

display(df.corr())   # correlation matrix

,col1,col2,col3
col1,1.000000e+00,-1.000000e+00,6.409876e-17
col2,-1.000000e+00,1.000000e+00,-6.409876e-17
col3,6.409876e-17,-6.409876e-17,1.000000e+00


15.What is causation? Explain difference between correlation and causation with an example.

ANS.Causation: One variable directly affects another.

Correlation: Two variables move together but may not have a cause-effect link.

Example:

Ice cream sales ↑ and drowning cases ↑ → correlated.

But cause is summer heat, not ice cream sales.

16.What is an Optimizer? What are different types of optimizers? Explain each with an example.

ANS.Optimizer: Algorithm that updates model parameters to minimize loss.

Types:

Gradient Descent – updates weights in opposite direction of gradient.

Stochastic Gradient Descent (SGD) – updates using one sample at a time.

Adam – adaptive learning rate + momentum (commonly used).

RMSProp – adjusts learning rate for each parameter.

17.What is sklearn.linear_model ?

ANS.A scikit-learn module for linear models such as:

LinearRegression, LogisticRegression, Ridge, Lasso, etc.

18.What does model.fit() do? What arguments must be given?

ANS.Trains the model on training data.

Arguments:

Features X_train

Labels y_train

19.What does model.predict() do? What arguments must be given?


ANS.Uses the trained model to predict outputs.

Argument: Feature set X_test

20.What are continuous and categorical variables?


ANS.Continuous: Numeric values with infinite possible outcomes (e.g., height, weight).

Categorical: Values divided into categories or labels (e.g., gender, color).

21.What is feature scaling? How does it help in Machine Learning?
ANS.Process of normalizing/standardizing data to a similar scale.

Helps algorithms (like gradient descent, SVM, KNN) converge faster and improve accuracy.

22.How do we perform scaling in Python?

ANS.

In [10]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import numpy as np # Import numpy

# Create a sample array X to demonstrate scaling
X = np.array([[1., -1., 2.],
              [2., 0., 0.],
              [0., 1., -1.]])

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

display(X_scaled)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

23.What is sklearn.preprocessing?

ANS.sklearn.preprocessing is a module in scikit-learn that provides tools to transform and prepare raw data before feeding it into a machine learning model.

24.How do we split data for model fitting (training and testing) in Python?

ANS.In Python, we usually split data into training (used to train the model) and testing (used to evaluate the model) sets using train_test_split from scikit-learn.

In [11]:
from sklearn.model_selection import train_test_split
import numpy as np

# Example dataset
X = np.array([[1], [2], [3], [4], [5], [6]])   # Features
y = np.array([1, 4, 9, 16, 25, 36])            # Labels (target values)

# Split data: 80% training, 20% testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training features:\n", X_train)
print("Testing features:\n", X_test)

Training features:
 [[6]
 [3]
 [5]
 [4]]
Testing features:
 [[1]
 [2]]


25.Explain data encoding?

ANS.Data encoding converts categorical/text data into numerical format for ML algorithms.

Methods: Label Encoding, One-Hot Encoding, Ordinal Encoding, Binary Encoding.